services:
  livekit:
    image: livekit/livekit-server:v1.12.0
    command: --config /etc/livekit/livekit.yaml
    network_mode: host
    restart: unless-stopped
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml:ro
